# Generated by Django 5.0.4 on 2024-05-03 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['title', 'created_at'],
                     'permissions': [('can_edit_publication_sign_product', 'может отменять публикацию продукта')],
                     'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
