# Generated by Django 5.0.4 on 2024-05-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['title', 'created_at'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
