# Generated by Django 5.0.3 on 2024-04-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_blog_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['title', 'created_at'], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
