# Generated by Django 5.0.4 on 2024-05-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_options_alter_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_edit_description_product', 'может менять описание любого продукта'), ('can_edit_category_product', 'может менять категорию любого продукта'), ('can_edit_publication_sign_product', 'может отменять публикацию продукта')], 'verbose_name': 'Продукты', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publication_sign',
            field=models.BooleanField(default=False, verbose_name='признак публикации'),
        ),
    ]
